version: '3.8'

services:
  # 主應用服務
  videoqna-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      # 基本設定
      - FLASK_ENV=development
      - PYTHONPATH=/app
      
      # 使用測試模式（不需要真實 Azure 服務）
      - LANGUAGE_MODEL=dummy
      - PROMPT_CONTENT_DB=chromadb
      - PROMPT_CONTENT_DB_NAME=vi-test-index
      
      # Video Indexer 測試設定
      - AccountName=test_account
      - ResourceGroup=test_group
      - SubscriptionId=test-subscription-id
      
      # 如果要使用真實 Azure 服務，取消下面的註解並填入真實值
      # - LANGUAGE_MODEL=openai
      # - PROMPT_CONTENT_DB=azure_search
      # - AZURE_OPENAI_API_KEY=your_api_key
      # - AZURE_OPENAI_SERVICE=your_service_name
      # - AZURE_OPENAI_CHATGPT_DEPLOYMENT=gpt-4o
      # - AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT=text-embedding-ada-002
      # - AZURE_SEARCH_SERVICE=your_search_service
      # - AZURE_SEARCH_KEY=your_search_key
    volumes:
      # 本機開發時掛載代碼，支援熱重載
      - ./app/backend:/app:delegated
      # 持久化 ChromaDB 數據
      - chroma_data:/app/.chroma
    networks:
      - videoqna-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/indexes"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 可選：Redis 作為 rate limiter 的存儲（代替內存存儲）
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - videoqna-network
  #   restart: unless-stopped

volumes:
  chroma_data:
  # redis_data:

networks:
  videoqna-network:
    driver: bridge
